[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y wget gnupg unzip",
    "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -",
    "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google-chrome.list",
    "apt-get update",
    "apt-get install -y google-chrome-stable",
    "apt-get clean"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"
